= Indexing Janet's C Source Code
:toc:

== Background

After making attempts to index Janet's C source code using https://github.com/universal-ctags/ctags[Universal Ctags] and https://github.com/tree-sitter/tree-sitter[tree-sitter], it became clear that neither approach was likely to yield good returns for a reasonable amount of effort.  Note that for some other C code bases, one of those approaches may be good enough, but if accuracy is desired with minimal work, I don't recommend either for Janet's C source.

What seems to be a better alternative is to use https://github.com/MaskRay/ccls[`ccls`], a C https://microsoft.github.io/language-server-protocol/[LSP] server.  (There is also https://clangd.llvm.org/[`clangd`], but I have not tried it out as much.  Depending on your environment, it may be that clangd is a better fit (e.g. for Windows, building clangd can be avoided, but ATM not so with ccls).)

What follows are some instructions in arriving at minimal setups for using ccls with Neovim, Emacs, Kakoune, or VSCode.

== Creation of `compile_commands.json`

Both LSP servers mentioned above depend on the existence of a file named `compile_comamnds.json` for proper functioning.  According to https://clang.llvm.org/docs/JSONCompilationDatabase.html[Clang's docs], it (or its content anyway) is:

> a format for specifying how to replay single compilations independently of the build system

This file is specific to a project can be created in more than one way.  The ways I've tried embed absolute paths unfortunately so I'm not going to upload mine (which might get out of date anyway).

First though, get https://github.com/janet-lang/janet[Janet]'s source:

----
git clone https://github.com/janet-lang/janet
----

=== Using `bear`

Install https://github.com/rizsotto/Bear[bear].  There might be https://repology.org/project/bear/versions[a package] already.

With `bear` installed, build `janet` using `make`, but with a slight change, e.g.

----
cd janet
# remove / modify following as desired
export PREFIX=$HOME/.local
make clean && bear -- make
----

`bear` should snoop on the building process and produce `compile_comamnds.json`.

=== Using `meson`

Janet can be built using `meson`.  https://github.com/MaskRay/ccls/wiki/Project-Setup#meson[`meson build` yields a `compile_commands.json`] in the `build` subdirectory.

With the file created, make a symlink to it from the repository root for janet, e.g.:

----
ln -s build/compile_commands.json compile_commands.json
----

Feel free to skip the following bit, but if the experience of navigation seems a bit cumbersome, consider returning to try the following modification.

=== Tweaking `compile_commands.json`

Whatever method chosen, once `compile_commands.json` has been made, consider editing `compile_commands.json` in the following manner.

One element of the list in `compile_commands.json` is perhaps extraneous for navigational purposes.  Specifically, the element (an object with at least the keys "directory", "file", and "output") that looks like:
----
{
  ...
  "directory": "...",
  "file": "...janet.c",
  "output": "...janet.o" // or "..._janet.c.o" for meson
},
----

I believe that corresponds to information about how `janet.o` was produced from `janet.c` (an amalmagated file).

Leaving that in `compile_commands.json` can lead to multiple candidates appearing when one asks one's editor to "jump to definition" because more than one possibility will exist.  I think this is because `janet.c` is, roughly, all of the content in `src/core/` concatenated together.  In my experience, removing it leads to less hectic navigation.

So using some editor, remove the relevant bit from `compile_commands.json`.

== Setup of ccls (C LSP Server) for use with Janet

Install https://github.com/MaskRay/ccls[ccls] and make sure it's available via `PATH`.  It may not be necessary to build from source -- see https://github.com/MaskRay/ccls/wiki/Build#system-specific-notes[here] for possible packages.

At this point the ground has been prepared for working via various editors.

## Editor Configuration

ATM, instructions are for Neovim, Emacs, Kakoune, and VSCode, but apparently https://github.com/MaskRay/ccls/wiki/Editor-Configuration[using other editors is also possible].

### Neovim

Apparently, there are https://github.com/MaskRay/ccls/wiki/Editor-Configuration[numerous options], but here just one will be described.  Be warned that I'm not a highly skilled user of Neovim and there might be better options.  If it's practical I recommend asking around for up-to-date recommendations on what to do.

1. Prepare to install https://github.com/neovim/nvim-lspconfig[`nvim-lspconfig`], e.g. if using vim-plug add the following to `~/.config/nvim/init.vim` or other appropriate location:
+
----
Plug 'neovim/nvim-lspconfig'
----

2. Also add:
+
----
lua <<EOF
require('lspconfig').ccls.setup{}
EOF
----

3. Install the plugin in Neovim via: `:PlugUpdate`

4. Open a Janet C source file (e.g. `src/core/vm.c`).

5. Verify the LSP connection via `:LspInfo`.

6. Put the cursor somewhere in a Janet-specific identifier and try: `:lua vim.lsp.buf.definition()`

7. See https://neovim.io/doc/user/lsp.html[`:help lsp`] and/or https://github.com/neovim/nvim-lspconfig#suggested-configuration[the Suggested configuration section of nvim-lspconfig's README] for more details.

### Emacs

Below are two ways to set up Emacs.

#### eglot

1. Install https://github.com/joaotavora/eglot[eglot] and configure your `.emacs`-equivalent.  Below is a https://github.com/raxod502/straight.el[`straight.el`]-based approach.
+
----
;;; eglot
(straight-use-package
  '(eglot :host github
          :repo "joaotavora/eglot"
          :file ("*.el")))

(use-package eglot
  :straight t)
----

2. Start Emacs and open some Janet C source file (e.g. `src/core/vm.c`).

3. `M-x eglot` to start ccls and connect to it.

4. Try `M-.` on a Janet-specific identifier to test jump-to-definition.

5. See the https://github.com/joaotavora/eglot#1-2-3[1-2-3 section of eglot's README] and https://github.com/MaskRay/ccls/wiki/eglot[the eglot Wiki page at the ccls repository] for more details.

#### lsp-mode and emacs-ccls

1. Install https://github.com/emacs-lsp/lsp-mode[lsp-mode] and https://github.com/MaskRay/emacs-ccls[emacs-ccls] and configure your `.emacs`-equivalent.  Below is a https://github.com/raxod502/straight.el[`straight.el`]-based approach.
+
----
;;; lsp-mode
(straight-use-package
 '(lsp-mode :host github
            :repo "emacs-lsp/lsp-mode"
            :file ("*.el" "clients" "docs" "features" "refcard" "scripts")))

(use-package lsp-mode
  :straight t
  :init
  ;; set prefix for lsp-command-keymap
  (setq lsp-keymap-prefix "C-c l")
  :commands lsp)

;;; emacs-ccls
(straight-use-package
 '(ccls :host github
        :repo "MaskRay/emacs-ccls"
        :file ("*.el")))

(use-package ccls
  :straight t)
----

2. Start Emacs and open some Janet C source file (e.g. `src/core/vm.c`).

3. `M-x lsp` to start ccls and connect to it.

4. Try `M-.` on a Janet-specific identifier to test jump-to-definition.

5. See https://emacs-lsp.github.io/lsp-mode/page/installation/[Installation info for LSP Mode] and https://github.com/MaskRay/ccls/wiki/lsp-mode[the lsp mode Wiki page at the ccls repository] for more details.

### Kakoune

1. Install https://github.com/kak-lsp/kak-lsp#installation[kak-lsp], and copy `kak-lsp.toml` to the directory `~/.config/kak-lsp/`.

2. Edit `~/.config/kak-lsp/kak-lsp.toml` so it has at least:
+
----
[language.c_cpp]
filetypes = ["c", "cpp"]
roots = ["compile_commands.json", ".ccls", ".git"]
command = "ccls"
args = ["--init={\"completion\":{\"detailedLabel\":false}}"]
----

3. Edit `kakrc` to contain at least:
+
----
eval %sh{kak-lsp --kakoune -s $kak_session}
hook global WinSetOption filetype=(c|cpp) %{
    lsp-enable-window
}

map global user l %{: enter-user-mode lsp<ret>} -docstring "LSP mode"
----

4. Start Kakoune and open some Janet C source file (e.g. `src/core/vm.c`).

5. Try `,ld` on a Janet-specific identifier to test jump-to-definition.

6. See the https://github.com/MaskRay/ccls/wiki/Kakoune[Kakoune page of the ccls wiki], the https://github.com/kak-lsp/kak-lsp/wiki/How-to-install-servers#c-c[C, C++ portion of the "How to install servers" page of the kak-lsp wiki], and/or https://discuss.kakoune.com/t/kak-lsp-ccls/750[MaskRay's post to Kakoune Community Hub] for more details.

### VSCode

1. Install the https://github.com/MaskRay/vscode-ccls[ccls VSCode Extension].  It's also available via the usual VSCode means.

2. With VSCode running, choose File -> Open Folder... to open Janet's source directory.

3. Open a C source file (e.g. `src/core/vm.c`).

4. Search for an identifier (e.g. `stack`).

5. Right-click on the identifier and choose "Go to Definition" from the context menu that should have appeared.

More details are at: https://github.com/MaskRay/ccls/wiki/Visual-Studio-Code[ccls' Visual Studio Code wiki page].
